name: landord_tenant
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0' # Dart SDK constraint

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4
  # Other dependencies...

dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter specific settings.

flutter:
  uses-material-design: true
